# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: BrowserStackParallel3DevicesAtTime

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Filter for tests'
        required: true
        default: '@Smoke and @Automated'
      device:
        description: 'Select the device to test'
        required: true
        type: choice
        options:
          - Xiaomi Redmi Note 11
          - Huawei P30
          - Oppo Reno 6
        default: 'Xiaomi Redmi Note 11'

jobs:
  test:
    runs-on: ubuntu-22.04
    container: crowdar/lippia:3.3.0.0-jdk17
    environment: Automation

    strategy:
      matrix:
        include:
          - device: "Xiaomi Redmi Note 11"
            android_version: "11"
          - device: "Huawei P30"
            android_version: "9"
          - device: "Oppo Reno 6"
            android_version: "11"

    env:
      BSUSER: ${{ secrets.BSUSER }}
      AUTHTOKEN: ${{ secrets.AUTHTOKEN }}
      BSDEVICE: ${{ matrix.device }}
      BSOS: ${{ matrix.android_version }}
      BSAPP: ${{ secrets.BSAPP }}
      LTM_GENERAL: ${{ secrets.LTM_GENERAL }}
      LTM_GENERAL_PASS: ${{ secrets.LTM_GENERAL_PASS }}

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4

      - name: Configuring JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List directories to verify path
        run: ls -al ~/.m2

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checking Maven dependencies
        run: mvn dependency:resolve

      - name: Setting environment variable
        run: echo "COMBINED_FILTER=${{ github.event.inputs.filter }}" >> $GITHUB_ENV

      - name: Debugging environment variables
        run: |
          echo "BSDEVICE: $BSDEVICE"
          echo "BSOS: $BSOS"
          echo "BSUSER: $BSUSER"
          echo "AUTHTOKEN: $AUTHTOKEN"
          echo "BSAPP: $BSAPP"
          echo "LTM_GENERAL: $LTM_GENERAL"
          echo "LTM_GENERAL_PASS: $LTM_GENERAL_PASS"

      - name: Running Maven clean test
        run: |
          echo "Running tests with filter: '$COMBINED_FILTER' on device: '$BSDEVICE' with OS version: '$BSOS'"
          mvn clean test -Dcrowdar.cucumber.filter="'$COMBINED_FILTER'" \
                         -Denv.BSDEVICE="${{ matrix.device }}" \
                         -Denv.BSOS="${{ matrix.android_version }}" \
                         -DTEST_MANAGER_RUN_NAME="AUTO-${{ matrix.device }}-${{ github.event.inputs.filter }}" \
                         -DLTM_GENERAL="${{ secrets.LTM_GENERAL }}" \
                         -DLTM_GENERAL_PASS="${{ secrets.LTM_GENERAL_PASS }}" \
                         -PBrowserStack -PAndroid

      - name: Uploading test reports
        uses: actions/upload-artifact@v4.3.4
        with:
          name: test-results
          path: target/reports/

      - name: Uploading surefire test reports
        uses: actions/upload-artifact@v4.3.4
        with:
          name: test-results-surefire
          path: target/surefire-reports/
