name: Maven test manual

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Filtro para los test'
        required: true
        default: '@Smoke and @Automated'

jobs:
  test:
    runs-on: ubuntu-22.04
    environment: Automation
    env:
      BSUSER: ${{ vars.BSUSER }}
      AUTHTOKEN: ${{ vars.AUTHTOKEN }}
      BSDEVICE: ${{ vars.BSDEVICE }}
      BSAPP: ${{ vars.BSAPP }}
      BSOS: ${{ vars.BSOS }}

    steps:
      - name: Checkout al repositorio
        uses: actions/checkout@v4

      - name: Configurando JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Ejecutando Maven clean test
        run: mvn clean test -Dcrowdar.cucumber.filter='${{ github.event.inputs.filter }}' -PBrowserStack -PAndroid

      - name: Subiendo informes del test
        uses: actions/upload-artifact@v4.3.4
        with:
          name: test-results
          path: target/reports/

      - name: Subiendo informes surefire del test
        uses: actions/upload-artifact@v4.3.4
        with:
          name: test-results
          path: target/surefire-reports/
