name: Maven test manual

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Filtro para los test'
        required: true
        default: '@Smoke and @Automated'

jobs:
  test:
    runs-on: ubuntu-22.04
    container: crowdar/lippia:3.3.0.0-jdk17
    environment: Automation
    env:
      BSUSER: ${{ vars.BSUSER }}
      AUTHTOKEN: ${{ vars.AUTHTOKEN }}
      BSDEVICE: ${{ vars.BSDEVICE }}
      BSAPP: ${{ vars.BSAPP }}
      BSOS: ${{ vars.BSOS }}

    steps:
      - name: Checkout al repositorio
        uses: actions/checkout@v4

      - name: Configurando JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache de las dependencias de Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verificando las dependencias de Maven
        run: mvn dependency:resolve  

      - name: Ejecutando Maven clean test
        run: mvn clean test -Dcrowdar.cucumber.filter='${{ github.event.inputs.filter }}' -PBrowserStack -PAndroid

      - name: Subiendo informes del test
        uses: actions/upload-artifact@v4.3.4
        with:
          name: test-results
          path: target/reports/

      - name: Subiendo informes surefire del test
        uses: actions/upload-artifact@v4.3.4
        with:
          name: test-results-surefire
          path: target/surefire-reports/
