name: Maven test manual

on:
  workflow_dispatch:
    branches:
      only:
        - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout al repositorio
        uses: actions/checkout@v4

      - name: Configurando JDK 17
        uses: actions/setup-java@v3

      - name: Ejecutando Maven clean test
        run: mvn clean test -Dcrowdar.cucumber.filter='@Smoke and @Automated' -PBrowserStack -PAndroid
